In [1]:
import numpy as np

In [2]:
# 행렬
data = np.matrix([[1000, 2000, 3000], [100, 200, 300]])

In [3]:
data

matrix([[1000, 2000, 3000],
        [ 100,  200,  300]])

In [31]:
data.sum()

6600

In [5]:
# axis = 0 == 세로
data.sum(axis = 0)

matrix([[1100, 2200, 3300]])

In [34]:
# axis = 1 == 가로
data.sum(axis = 1)

matrix([[6000],
        [ 600]])

In [33]:
data.mean()

1100.0

In [30]:
data.mean(axis = 0)

matrix([[ 550., 1100., 1650.]])

In [35]:
data.mean(axis = 1)

matrix([[2000.],
        [ 200.]])

In [38]:
x = np.matrix([[1, 2], [3, 4]])
x.shape

(2, 2)

In [39]:
x

matrix([[1, 2],
        [3, 4]])

In [40]:
y = np.matrix([[3, 4], [3, 10]])
y.shape

(2, 2)

In [41]:
y

matrix([[ 3,  4],
        [ 3, 10]])

In [44]:
result = np.add(x, y)
result.shape

(2, 2)

In [45]:
result

matrix([[ 4,  6],
        [ 6, 14]])

In [46]:
x + y

matrix([[ 4,  6],
        [ 6, 14]])

In [47]:
x - y

matrix([[-2, -2],
        [ 0, -6]])

In [78]:
a = np.matrix([[1, 1, 0, 3],[2, 1, 1, 4], [1, 0, 0, 2]])
a.shape

(3, 4)

In [79]:
a

matrix([[1, 1, 0, 3],
        [2, 1, 1, 4],
        [1, 0, 0, 2]])

In [80]:
b = np.matrix([[2000, 3000, 2000, 500]])
b.shape

(1, 4)

In [81]:
b

matrix([[2000, 3000, 2000,  500]])

In [68]:
b.T

matrix([[2000],
        [3000],
        [2000],
        [ 500]])

In [83]:
b.T.shape

(4, 1)

In [72]:
result = np.matmul(a, b.T)
result

matrix([[ 6500],
        [11000],
        [ 3000]])

In [73]:
result.sum()

20500

In [75]:
a * b.T

matrix([[ 6500],
        [11000],
        [ 3000]])

In [76]:
a + b.T

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [56]:
a = np.matrix([[1,0], [0, 1]])
a

matrix([[1, 0],
        [0, 1]])

In [57]:
b = np.matrix([[1,2]])
b

matrix([[1, 2]])

In [59]:
np.matmul(a, b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [61]:
# tranpose == T
b.T

matrix([[1],
        [2]])

In [62]:
np.matmul(a,b.T)

matrix([[1],
        [2]])

In [64]:
np.dot(a, b.T)

matrix([[1],
        [2]])

In [84]:
a = np.matrix([[1,2], [3, 4]])
a

matrix([[1, 2],
        [3, 4]])

In [85]:
a.T

matrix([[1, 3],
        [2, 4]])

In [87]:
b = np.matrix([[1,2], [3,4], [5,6]])
b

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [88]:
b.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [6]:
x1 = np.array([1, 2, 3])
x1

array([1, 2, 3])

In [7]:
y1 = np.array([3, 6, 9])
y1

array([3, 6, 9])

In [13]:
# element-wise operation
x1 + y1

array([ 4,  8, 12])

In [17]:
x1 - y1

array([-2, -4, -6])

In [8]:
x1 * y1

array([ 3, 12, 27])

In [9]:
x1 ** y1

array([    1,    64, 19683], dtype=int32)

In [18]:
x1 / y1

array([0.33333333, 0.33333333, 0.33333333])

In [10]:
# 벡터의 내적
np.dot(x1, y1)

42

In [11]:
# 벡터의 외적
np.cross(x1, y1)

array([0, 0, 0])

In [12]:
# 작동하지 않음
np.sum(x1, y1)

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
# list 로 바꾸면 계산이 달라짐
a = [1, 2, 3]
a

[1, 2, 3]

In [15]:
b = [3, 6, 9]
b

[3, 6, 9]

In [16]:
a + b

[1, 2, 3, 3, 6, 9]

In [19]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [20]:
np.dot(a, b)

42

In [23]:
x2 = np.array([180, 80, 30])
x2

array([180,  80,  30])

In [24]:
y2 = np.array([165, 60, 25])
y2

array([165,  60,  25])

In [25]:
np.dot(x2, y2)

35250

In [27]:
np.cross(x2, y2)

array([  200,   450, -2400])

In [ ]:
# Vectorization

In [91]:
a = np.random.rand(1000000)

In [92]:
b = np.random.rand(1000000)

In [101]:
%%time
s = 0

for i in range(100000):
    s += a[i] * b[i]
    
s

Wall time: 43.9 ms


In [102]:
%%time
s = np.dot(a, b)

s

Wall time: 0 ns


In [103]:
m = 2000
n = 1000
p = 1

In [105]:
x = np.random.rand(m, n)
x.shape

(2000, 1000)

In [107]:
v = np.random.rand(n, p)
v.shape

(1000, 1)

In [108]:
u = np.zeros((m, p))
u.shape

(2000, 1)

In [110]:
%%time
for i in range(m):
    for j in range(n):
        u[i] += x[i][j] * v[j]
u

Wall time: 5.57 s


In [113]:
%%time
u = np.dot(x, v)

u

Wall time: 998 µs


In [114]:
import math

n = 100000

In [117]:
v = np.random.rand(n)
v.shape

(100000,)

In [120]:
u = np.zeros((n, 1))

u.shape

(100000, 1)

In [123]:
%%time
for i in range(n):
    u[i] = math.exp(v[i])
    
u

Wall time: 46.9 ms


In [126]:
%%time
u = np.exp(v)

u

Wall time: 0 ns
